### ISSUE TITLE
ZingChart Maps ZC not defined

### ISSUE THREAD

**Issue by gmiked** [zingchart/zingchart-angular#22]
I am trying to use the map chart component in one of the feature modules.  When importing js files "zingchart/modules/zingchart-maps.min.js" and "zingchart/modules/zingchart-maps-usa.min.js" for the ZingChartMap into the .component.ts file, I get the below error.  I am on Angular 12 with zingchart "zingchart": "*" and "zingchart-angular": "^1.0.9", installed.  I have also added "postinstall": "ngcc" in my package.json file.  Is there anything I am missing in order to use the zingchartmap?  Every other component so far works except the map.

`core.js:6498 ERROR Error: Uncaught (in promise): ReferenceError: ZC is not defined
ReferenceError: ZC is not defined
    at Object.6272 (zingchart-maps.min.js:8:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.4448 (browse.component.html:1:21)
    at __webpack_require__ (bootstrap:19:1)
    at Module.2208 (zingchart-es6.min.js:9:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.7579 (airport-routing.module.ts:16:25)
    at Function.__webpack_require__ (bootstrap:19:1)
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28692:1)
    at resolvePromise (zone.js:1213:1)
    at resolvePromise (zone.js:1167:1)
    at zone.js:1279:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28679:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)`

**Comment by gmiked** [comment]
Ok, I was able to get around this, by doing one of the below.  I am not sure why this is a problem only for using the maps.

1.    I needed to import the ZingChartAngular module to the app.module.ts file and the feature module ts file.

2.    I needed to import ZingChartAngular module to the feature module ts file, and only export the ZingChartAngular module in app.module.ts.

**Comment by gmiked** [comment]
I was also able to resolve this by importing ZingChartAngular module before the FeatureModuleRouting Module.
